/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coddit2;
import coddit2.managers.EditorTabManager;
import coddit2.managers.ExecutionManager;
import coddit2.managers.ProjectExplorer;
import coddit2.search.FindReplaceBar;
import coddit2.utils.ConfigManager;
import coddit2.utils.FileHandler;
import com.formdev.flatlaf.*;
import javax.swing.*;
import java.awt.Color;


/**
 *
 * @author vince
 */
public class Coddit2 extends javax.swing.JFrame {

    private ConfigManager configManager;
    private javax.swing.JMenu openRecentMenu;
    private javax.swing.JLabel statusLabel;
    
    private ProjectExplorer projectExplorer;
    private EditorTabManager editorTabManager;
    private ExecutionManager executionManager;
    private FindReplaceBar findReplaceBar;

    /**
     * Creates new form Coddit2
     */
    public Coddit2() {
        initComponents();
        
        // Re-layout components to allow full-width status bar
        getContentPane().remove(RunBar);
        getContentPane().remove(HorizontalSep);
        
        javax.swing.JPanel mainContainer = new javax.swing.JPanel(new java.awt.BorderLayout());
        mainContainer.add(HorizontalSep, java.awt.BorderLayout.CENTER);
        mainContainer.add(RunBar, java.awt.BorderLayout.EAST);
        
        getContentPane().add(mainContainer, java.awt.BorderLayout.CENTER);
        
        configManager = new ConfigManager();
        setupRecentMenu();
        setupStatusBar();
        setupOutputTabHeader();
        
        // Initialize Managers
        projectExplorer = new ProjectExplorer(this, FileTree, HorizontalSep);
        editorTabManager = new EditorTabManager(this, EditorTabs);
        executionManager = new ExecutionManager(this, editorTabManager, OutputTab, OutputPane, FunErrCode);
        findReplaceBar = new FindReplaceBar(editorTabManager);
        
        // Add Search Bar
        javax.swing.JPanel editorContainer = new javax.swing.JPanel(new java.awt.BorderLayout());
        editorContainer.add(EditorTabs, java.awt.BorderLayout.CENTER);
        editorContainer.add(findReplaceBar, java.awt.BorderLayout.SOUTH);
        VerticalSep1.setTopComponent(editorContainer);
        
        // Check for first instance and load last project
        if (configManager.acquireInstanceLock()) {
            String lastProj = configManager.getLastProject();
            if (lastProj != null) {
                java.io.File projFile = new java.io.File(lastProj);
                if (projFile.exists()) {
                    projectExplorer.updateFileTree(projFile);
                }
            }
        }
        
        // Initialize File Tree
        projectExplorer.setupFileTree();

        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        this.getRootPane().putClientProperty("JRootPane.menuBarEmbedded", true);
        
        if (projectExplorer.getCurrentProjectFolder() != null) {
            this.setTitle("Coddit - " + projectExplorer.getCurrentProjectFolder().getName());
        } else {
            this.setTitle("Coddit");
        }
        
        this.setLocationRelativeTo(null); 

        // Add Tab on New Start
        editorTabManager.createNewTab();
        
        // Close Tab Shortcut (Ctrl+W)
        javax.swing.JRootPane rootPane = this.getRootPane();
        javax.swing.InputMap inputMap = rootPane.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);
        javax.swing.ActionMap actionMap = rootPane.getActionMap();
        
        inputMap.put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK), "CloseTab");
        actionMap.put("CloseTab", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                int index = EditorTabs.getSelectedIndex();
                if (index != -1) {
                    editorTabManager.closeTab(index);
                }
            }
        });
        
        
        this.getRootPane().putClientProperty("JRootPane.titleBarBackground", new Color(0xDBDBDB));
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        RunBar = new javax.swing.JPanel();
        RunCode = new javax.swing.JButton();
        StopCode = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        HorizontalSep = new javax.swing.JSplitPane();
        VerticalSep1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        OutputPane = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        OutputTab = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        TerminalTab = new javax.swing.JEditorPane();
        EditorTabs = new javax.swing.JTabbedPane();
        FileTreeScroll = new javax.swing.JScrollPane();
        FileTree = new javax.swing.JTree();
        WindowMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewFile = new javax.swing.JMenuItem();
        OpenProj = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SaveFile = new javax.swing.JMenuItem();
        SaveFileAs = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ExitIDE = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        undoItem = new javax.swing.JMenuItem();
        redoItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        CopyText = new javax.swing.JMenuItem();
        CutText = new javax.swing.JMenuItem();
        PasteText = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        FindMenu = new javax.swing.JMenuItem();
        ReplaceMenu = new javax.swing.JMenuItem();
        TASTEMenu = new javax.swing.JMenu();
        FunErrCode = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 480));

        RunBar.setBackground(new java.awt.Color(234, 234, 234));
        RunBar.setLayout(new java.awt.GridBagLayout());

        RunCode.setBackground(new java.awt.Color(234, 234, 234));
        RunCode.setFont(new java.awt.Font("Segoe Fluent Icons", 1, 18)); // NOI18N
        RunCode.setForeground(new java.awt.Color(0, 153, 0));
        RunCode.setText("");
        RunCode.setToolTipText("Run Code");
        RunCode.setBorderPainted(false);
        RunCode.setFocusable(false);
        RunCode.setMaximumSize(new java.awt.Dimension(35, 35));
        RunCode.setPreferredSize(new java.awt.Dimension(35, 35));
        RunCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        RunBar.add(RunCode, gridBagConstraints);

        StopCode.setBackground(new java.awt.Color(234, 234, 234));
        StopCode.setFont(new java.awt.Font("Segoe Fluent Icons", 1, 18)); // NOI18N
        StopCode.setForeground(new java.awt.Color(255, 0, 0));
        StopCode.setText("");
        StopCode.setToolTipText("Stop Program");
        StopCode.setBorderPainted(false);
        StopCode.setFocusable(false);
        StopCode.setMaximumSize(new java.awt.Dimension(35, 35));
        StopCode.setPreferredSize(new java.awt.Dimension(35, 35));
        StopCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopCodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        RunBar.add(StopCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 1.0;
        RunBar.add(filler1, gridBagConstraints);

        getContentPane().add(RunBar, java.awt.BorderLayout.EAST);

        HorizontalSep.setBackground(new java.awt.Color(234, 234, 234));
        HorizontalSep.setResizeWeight(0.3);
        HorizontalSep.setToolTipText("");

        VerticalSep1.setBackground(new java.awt.Color(228, 228, 228));
        VerticalSep1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        VerticalSep1.setResizeWeight(0.7);

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jEditorPane1.setPreferredSize(null);
        jScrollPane1.setViewportView(jEditorPane1);

        VerticalSep1.setTopComponent(jScrollPane1);

        OutputPane.setBackground(new java.awt.Color(255, 255, 255));
        OutputPane.setFocusable(false);
        OutputPane.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        OutputPane.setOpaque(true);

        jScrollPane3.setBackground(new java.awt.Color(102, 102, 0));
        jScrollPane3.setBorder(null);
        jScrollPane3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        OutputTab.setEditable(false);
        OutputTab.setBackground(new java.awt.Color(255, 255, 255));
        OutputTab.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(OutputTab);

        OutputPane.addTab("Output", jScrollPane3);

        jScrollPane4.setBackground(new java.awt.Color(102, 102, 0));
        jScrollPane4.setBorder(null);

        TerminalTab.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(TerminalTab);

        OutputPane.addTab("Terminal", jScrollPane4);

        VerticalSep1.setRightComponent(OutputPane);

        EditorTabs.setBackground(new java.awt.Color(255, 255, 255));
        EditorTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        EditorTabs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        EditorTabs.setOpaque(true);
        EditorTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EditorTabsStateChanged(evt);
            }
        });
        VerticalSep1.setTopComponent(EditorTabs);

        HorizontalSep.setRightComponent(VerticalSep1);

        FileTreeScroll.setBorder(null);

        FileTree.setBackground(new java.awt.Color(234, 234, 234));
        FileTree.setBorder(null);
        FileTree.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FileTree.setModel(null);
        FileTreeScroll.setViewportView(FileTree);

        HorizontalSep.setLeftComponent(FileTreeScroll);

        getContentPane().add(HorizontalSep, java.awt.BorderLayout.CENTER);

        WindowMenu.setBackground(new java.awt.Color(212, 212, 212));
        WindowMenu.setBorder(null);
        WindowMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        WindowMenu.setName(""); // NOI18N

        FileMenu.setText("File");
        FileMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        NewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NewFile.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        NewFile.setText("New File");
        NewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileActionPerformed(evt);
            }
        });
        FileMenu.add(NewFile);

        OpenProj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        OpenProj.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        OpenProj.setText("Open Project");
        OpenProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenProjActionPerformed(evt);
            }
        });
        FileMenu.add(OpenProj);
        FileMenu.add(jSeparator3);

        SaveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveFile.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SaveFile.setText("Save");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        FileMenu.add(SaveFile);

        SaveFileAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveFileAs.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SaveFileAs.setText("Save As.");
        SaveFileAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileAsActionPerformed(evt);
            }
        });
        FileMenu.add(SaveFileAs);
        FileMenu.add(jSeparator1);

        ExitIDE.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ExitIDE.setText("Exit");
        ExitIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitIDEActionPerformed(evt);
            }
        });
        FileMenu.add(ExitIDE);

        WindowMenu.add(FileMenu);

        EditMenu.setText("Edit");
        EditMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        undoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        undoItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        undoItem.setText("Undo");
        undoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoItemActionPerformed(evt);
            }
        });
        EditMenu.add(undoItem);

        redoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        redoItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        redoItem.setText("Redo");
        redoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoItemActionPerformed(evt);
            }
        });
        EditMenu.add(redoItem);
        EditMenu.add(jSeparator2);

        CopyText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CopyText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CopyText.setText("Copy");
        EditMenu.add(CopyText);

        CutText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CutText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CutText.setText("Cut");
        EditMenu.add(CutText);

        PasteText.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PasteText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        PasteText.setText("Paste");
        EditMenu.add(PasteText);
        EditMenu.add(jSeparator4);

        FindMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FindMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FindMenu.setText("Find");
        FindMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindMenuActionPerformed(evt);
            }
        });
        EditMenu.add(FindMenu);

        ReplaceMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ReplaceMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ReplaceMenu.setText("Replace");
        ReplaceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplaceMenuActionPerformed(evt);
            }
        });
        EditMenu.add(ReplaceMenu);

        WindowMenu.add(EditMenu);

        TASTEMenu.setText("TASTE");
        TASTEMenu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        FunErrCode.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        FunErrCode.setSelected(true);
        FunErrCode.setText("Fun Error Codes");
        TASTEMenu.add(FunErrCode);

        WindowMenu.add(TASTEMenu);

        setJMenuBar(WindowMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenProjActionPerformed
        java.io.File folder = FileHandler.openDirectoryChooser(this);
        if (folder != null) {
            projectExplorer.updateFileTree(folder);
            configManager.addRecentProject(folder.getAbsolutePath());
            updateRecentMenu();
        }
    }//GEN-LAST:event_OpenProjActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        javax.swing.text.JTextComponent textArea = editorTabManager.getCurrentTextArea();
        if (textArea != null) {
            java.io.File file = (java.io.File) textArea.getClientProperty("file");
            if (file != null) {
                try {
                    FileHandler.saveFile(file, textArea.getText());
                    editorTabManager.setTabTitleBold(textArea, false);
                } catch (java.io.IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error saving file: " + ex.getMessage());
                }
            } else {
                SaveFileAsActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_SaveFileActionPerformed

    private void ExitIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitIDEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitIDEActionPerformed

    private void SaveFileAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileAsActionPerformed
        javax.swing.text.JTextComponent textArea = editorTabManager.getCurrentTextArea();
        if (textArea != null) {
            java.io.File file = (java.io.File) textArea.getClientProperty("file");
            if (file == null) {
                file = FileHandler.saveFileChooser(this);
            }
            
            if (file != null) {
                try {
                    FileHandler.saveFile(file, textArea.getText());
                    textArea.putClientProperty("file", file);
                    
                    // Update tab title
                    int index = EditorTabs.getSelectedIndex();
                    editorTabManager.updateTabTitle(index, file.getName());
                    editorTabManager.setTabTitleBold(textArea, false);
                    
                } catch (java.io.IOException ex) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error saving file: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_SaveFileAsActionPerformed

    private void NewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileActionPerformed
        editorTabManager.createNewTab();
    }//GEN-LAST:event_NewFileActionPerformed

    private void ReplaceMenuActionPerformed(java.awt.event.ActionEvent evt) {                                               
        findReplaceBar.showSearchBar(true);
    }                                          

    private void FindMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        findReplaceBar.showSearchBar(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void EditorTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EditorTabsStateChanged
        editorTabManager.updateCursorPosition();
    }//GEN-LAST:event_EditorTabsStateChanged

    private void RunCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunCodeActionPerformed
        executionManager.runCode();
    }//GEN-LAST:event_RunCodeActionPerformed

    private void StopCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopCodeActionPerformed
        executionManager.stopCode();
    }//GEN-LAST:event_StopCodeActionPerformed

    private void undoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoItemActionPerformed
        javax.swing.text.JTextComponent textArea = editorTabManager.getCurrentTextArea();
            if (textArea != null) {
                javax.swing.undo.UndoManager um = (javax.swing.undo.UndoManager) textArea.getClientProperty("undoManager");
                if (um != null && um.canUndo()) um.undo();
        }
    }//GEN-LAST:event_undoItemActionPerformed

    private void redoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoItemActionPerformed
        javax.swing.text.JTextComponent textArea = editorTabManager.getCurrentTextArea();
            if (textArea != null) {
                javax.swing.undo.UndoManager um = (javax.swing.undo.UndoManager) textArea.getClientProperty("undoManager");
                if (um != null && um.canRedo()) um.redo();
        }
    }//GEN-LAST:event_redoItemActionPerformed
     
    private void setupRecentMenu() {
        openRecentMenu = new javax.swing.JMenu("Open Recent");
        openRecentMenu.setFont(new java.awt.Font("Roboto", 0, 12));
        FileMenu.add(openRecentMenu, 2); // Insert after Open Project
        updateRecentMenu();
    }

    private void updateRecentMenu() {
        openRecentMenu.removeAll();
        java.util.List<String> recent = configManager.getRecentProjects();
        if (recent.isEmpty()) {
            javax.swing.JMenuItem item = new javax.swing.JMenuItem("No Recent Projects");
            item.setEnabled(false);
            openRecentMenu.add(item);
        } else {
            for (String path : recent) {
                javax.swing.JMenuItem item = new javax.swing.JMenuItem(path);
                item.setFont(new java.awt.Font("Roboto", 0, 12));
                item.addActionListener(e -> {
                    java.io.File folder = new java.io.File(path);
                    if (folder.exists()) {
                        projectExplorer.updateFileTree(folder);
                        configManager.addRecentProject(path);
                        updateRecentMenu();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Project directory not found.");
                    }
                });
                openRecentMenu.add(item);
            }
        }
    }

    public void setStatusText(String text) {
        statusLabel.setText(text);
    }

    public void openFileInTab(java.io.File file) {
        editorTabManager.openFileInTab(file);
    }

    public void createNewFile() {
        projectExplorer.createNewFile();
    }

    public void deleteFile() {
        projectExplorer.deleteFile();
    }

    public void refreshFileTree() {
        projectExplorer.refreshFileTree();
    }



    private void setupStatusBar() {
        javax.swing.JPanel statusBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        statusBar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, javax.swing.UIManager.getColor("Component.borderColor")));
        statusLabel = new javax.swing.JLabel("Line: 1, Column: 1");
        statusLabel.setFont(new java.awt.Font("Roboto", 0, 11));
        statusBar.add(statusLabel);
        getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);
    }

    private void setupOutputTabHeader() {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        panel.setOpaque(false);
        panel.add(new javax.swing.JLabel("Output"));
        
        javax.swing.JButton clearBtn = new javax.swing.JButton(""); // Trash icon
        clearBtn.setFont(new java.awt.Font("Segoe MDL2 Assets", 0, 12));
        clearBtn.setToolTipText("Clear Output");
        clearBtn.setBorderPainted(false);
        clearBtn.setContentAreaFilled(false);
        clearBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(e -> OutputTab.setText(""));
        
        panel.add(clearBtn);
        
        int index = OutputPane.indexOfComponent(jScrollPane3);
        if (index != -1) {
            OutputPane.setTabComponentAt(index, panel);
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Adjust DPI Scaling
        System.setProperty("sun.java2d.uiScale", "1.75");
        System.setProperty("sun.java2d.dpiaware", "true");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coddit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coddit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coddit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coddit2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coddit2().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CopyText;
    private javax.swing.JMenuItem CutText;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JTabbedPane EditorTabs;
    private javax.swing.JMenuItem ExitIDE;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JTree FileTree;
    private javax.swing.JScrollPane FileTreeScroll;
    private javax.swing.JMenuItem FindMenu;
    private javax.swing.JCheckBoxMenuItem FunErrCode;
    private javax.swing.JSplitPane HorizontalSep;
    private javax.swing.JMenuItem NewFile;
    private javax.swing.JMenuItem OpenProj;
    private javax.swing.JTabbedPane OutputPane;
    private javax.swing.JEditorPane OutputTab;
    private javax.swing.JMenuItem PasteText;
    private javax.swing.JMenuItem ReplaceMenu;
    private javax.swing.JPanel RunBar;
    private javax.swing.JButton RunCode;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JMenuItem SaveFileAs;
    private javax.swing.JButton StopCode;
    private javax.swing.JMenu TASTEMenu;
    private javax.swing.JEditorPane TerminalTab;
    private javax.swing.JSplitPane VerticalSep1;
    private javax.swing.JMenuBar WindowMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem redoItem;
    private javax.swing.JMenuItem undoItem;
    // End of variables declaration//GEN-END:variables
}
